import { Raleway } from "next/font/google";
import './globals.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({
  subsets: ['latin'],
  display: "swap"
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={raleway.className}>
      <body style={styles.body} >{children}</body>
    </html>
  );
}

const styles = {
  body: {
    padding: 0,
    margin: 0,
    boxSizing: 'border-box',
  }
}
